### ISSUE TITLE
Status Bar not visible with dark background

### ISSUE THREAD

**Issue by marco9446** [ottop/yam_launcher#15]
First of all thank you for the very nice launcher.

I only have a small issue. I'm currently using the background color option to set the background to black. 
If I do that, and the phone is in light mode, the status bar disappear because it's black text on black background.

Would it be possible to set the status bar text color based on the background?

**Comment by ottop** [comment]
Thanks for the feedback.

I'm not sure if this is possible, but I'll look into it.

**Comment by ottop** [comment]
Turns out status bar text color can be changed, but only between black and white. I have now implemented this in such a way that the status bar text color is set according to the text color in the launcher. The implementation is as follows:

Light text color -> White status bar text
Dark text color -> Black status bar text
Material text color -> Depends on whether using light or dark theme. White for dark theme, black for light theme.

**Comment by ottop** [comment]
This has now been released in 1.6.
